'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const file = path.resolve(__dirname, '../ui/graph-scene.js');
assert.ok(fs.existsSync(file), 'The spatial graph scene must exist');
const G = require(file);
const graph = {nodes: Array.from({length: 120}, (_, i) => ({id: 'n'+i, label: 'Idea '+i, kind: i%2?'claim':'concept', community: i%4})), edges: Array.from({length:119}, (_,i)=>({id:'e'+i, source:'n'+i,target:'n'+(i+1),relation:i%2?'supports':'contradicts'}))};
const before=JSON.stringify(graph);
const layout=G.layout(graph);
assert.equal(Object.keys(layout).length,120);
assert.deepEqual(layout,G.layout(graph),'Layout must be deterministic');
assert.ok(Object.values(layout).every(p=>[p.x,p.y,p.z].every(Number.isFinite)));
assert.ok(new Set(Object.values(layout).map(p=>p.z)).size>20,'Depth must be real, not a background image');
assert.equal(JSON.stringify(graph),before,'Layout must never modify evidence');
const a=G.project({x:110,y:30,z:75},{yaw:0,pitch:0,zoom:1,panX:0,panY:0});
const b=G.project({x:110,y:30,z:75},{yaw:0.6,pitch:0.2,zoom:1,panX:0,panY:0});
assert.notEqual(a.x,b.x,'Orbit must change projection');
assert.ok([a.x,a.y,a.scale,a.depth].every(Number.isFinite));
assert.equal(G.nodeStyle('claim').color===G.nodeStyle('concept').color,false);
assert.notEqual(G.nodeStyle('source').shape,G.nodeStyle('claim').shape);
assert.notEqual(G.edgeStyle('supports').color,G.edgeStyle('contradicts').color);
assert.notEqual(G.edgeStyle('supports').dash,G.edgeStyle('contradicts').dash);
assert.equal(G.edgeStyle('unfamiliar_relation').family,'Other');
const view=G.view(graph,{focus:'n50',hops:1});
assert.deepEqual(view.nodes.map(n=>n.id).sort(),['n49','n50','n51']);
assert.equal(G.view(graph,{query:'Idea 119'}).nodes.some(n=>n.id==='n119'),true);
assert.ok(G.view(graph,{kind:'claim'}).nodes.every(n=>n.kind==='claim'));
assert.ok(G.view(graph,{relation:'contradicts'}).edges.every(e=>e.relation==='contradicts'));
const dense={nodes:Array.from({length:1200},(_,i)=>({id:'d'+i,label:'Dense '+i,kind:'concept',community:i%8})),edges:[]};
const clustered=G.view(dense,{cluster:true});
assert.ok(clustered.nodes.length<=60);
assert.equal(clustered.nodes.reduce((n,g)=>n+(g.members?.length||1),0),1200,'Overview must account for every node');
assert.ok(clustered.nodes.every(n=>n.members?.length));
const limited=G.view(dense,{limit:200});
assert.equal(limited.nodes.length,200);
assert.equal(limited.hidden,1000,'Any display limit must be explicit');
const bad={nodes:[{id:'a',label:'a'},{id:'b',label:'b'}],edges:[{id:'x',source:'a',target:'missing'}]};
assert.equal(G.view(bad,{}).edges.length,0);
assert.ok(G.path({x:0,y:0},{x:0,y:0},0).includes('C'),'Self loops need visible curves');
assert.deepEqual(G.view({nodes:[],edges:[]},{}).nodes,[]);
console.log('PASS: spatial projection, deterministic layout, read-only views, shapes, relationships, focus, search, clustering, explicit limits and degenerate edges.');
