/* Graph Atlas: an editable, perspective-projected SVG scene. Works offline in WebView2. */
'use strict';
const atlasStates=new Map();
let atlasFrame=0, atlasDirty=false;
function atlasState(){
 const id=state.p?.id||'';
 if(!atlasStates.has(id)){
  let saved={};try{saved=JSON.parse(storage.getItem('graphpaper.atlas.'+id)||'{}');}catch{}
  if(!saved||typeof saved!=='object')saved={};
  if(saved.camera&&Object.values(saved.camera).some(v=>typeof v!=='boolean'&&!Number.isFinite(v)))saved.camera={};
  atlasStates.set(id,{camera:{yaw:.18,pitch:-.13,zoom:1,panX:0,panY:0,flat:false,...saved.camera},spacing:1,labels:'smart',kind:'',relation:'',focus:0,members:null,cluster:(state.p?.graph.nodes.length||0)>160,positions:Object.create(null),key:'',fit:true,expanded:false,...(Number.isFinite(saved.spacing)?{spacing:GraphScene.clamp(saved.spacing,.6,2.6)}:{})});
 }
 return atlasStates.get(id);
}
function atlasPersist(){if(!state.p)return;const s=atlasState();storage.setItem('graphpaper.atlas.'+state.p.id,JSON.stringify({camera:s.camera,spacing:s.spacing}));}
function atlasSchedule(){if(!atlasFrame)atlasFrame=requestAnimationFrame(()=>{atlasFrame=0;drawGraph();});}
function atlasOptions(values,current,empty){return `<option value="">${esc(empty)}</option>`+[...new Set(values)].sort().map(v=>`<option value="${esc(v)}" ${current===v?'selected':''}>${esc(v.replaceAll('_',' '))}</option>`).join('');}
graphHTML=function(){
 const s=atlasState(),g=state.p.graph;
 return `<section class="atlas-shell ${s.expanded?'atlas-expanded':''}" aria-label="Graph Atlas"><div class="atlas-main panel">
 <header class="atlas-toolbar"><div class="atlas-search">${icon('search')}<input id="graph-search" aria-label="Find an idea in the graph" placeholder="Find an idea, claim or relationship…" value="${esc(state.search)}"></div><div class="atlas-toolbar-actions">${ibtn('Add node','atlas-add-node','plus')}${ibtn('Connect nodes','atlas-connect','link')}${ibtn('Undo last graph edit','atlas-undo','back')}${ibtn(s.expanded?'Exit expanded graph':'Expand graph','atlas-expand','expand')}</div></header>
 <div class="atlas-filters"><select id="atlas-kind" aria-label="Filter node type">${atlasOptions(g.nodes.map(n=>n.kind),s.kind,'All node types')}</select><select id="atlas-relation" aria-label="Filter relationship">${atlasOptions(g.edges.map(e=>e.relation),s.relation,'All relationships')}</select><select id="atlas-focus" aria-label="Focus neighborhood"><option value="0" ${!s.focus?'selected':''}>Whole graph</option><option value="1" ${s.focus===1?'selected':''}>1-hop neighborhood</option><option value="2" ${s.focus===2?'selected':''}>2-hop neighborhood</option></select><button class="button small" data-action="atlas-clusters" aria-pressed="${s.cluster}">Clusters</button></div>
 <div class="atlas-stage"><svg id="graph-svg" class="graph-canvas atlas-canvas" viewBox="0 0 1100 720" role="group" aria-label="Interactive spatial knowledge graph" tabindex="0"></svg>
 <div class="atlas-view-hint"><span class="atlas-live-dot"></span><span id="atlas-hint">Drag to orbit · Shift-drag to pan · scroll to zoom</span></div>
 <div class="atlas-view-tools"><div class="atlas-mode"><button data-action="atlas-3d" aria-pressed="${!s.camera.flat}">3D</button><button data-action="atlas-2d" aria-pressed="${s.camera.flat}">2D</button></div>${ibtn('Zoom in','zoom-in','plus')}${ibtn('Zoom out','zoom-out','minus')}${ibtn('Fit graph','fit-graph','expand')}${ibtn('Find a path','find-path','branch')}</div>
 <div id="atlas-minimap" class="atlas-minimap" aria-label="Graph overview"></div>
 <div id="atlas-empty" class="atlas-empty hidden"><strong>No nodes in this view.</strong><span>Clear the filters, or add your first idea.</span>${btn('Reset view','atlas-reset','refresh','small')}</div></div>
 <div class="atlas-bottom"><span id="graph-visibility" role="status"></span><button class="text-link" data-action="atlas-reset">Reset view</button></div>
 <div class="atlas-legend"><div class="atlas-legend-nodes">${['concept','claim','source','evidence','person','event'].map(k=>`<span><i class="atlas-symbol ${GraphScene.nodeStyle(k).shape}" style="--node-color:${GraphScene.nodeStyle(k).color}"></i>${GraphScene.nodeStyle(k).name}</span>`).join('')}</div><div class="atlas-legend-edges">${GraphScene.families.map(f=>`<span><svg viewBox="0 0 28 10" aria-hidden="true"><path d="M1 5H23m-4-3 5 3-5 3" stroke="${f.color}" stroke-dasharray="${f.dash}" fill="none"/></svg>${esc(f.family)}</span>`).join('')}</div></div>
 <details class="atlas-view-settings"><summary>Layout & readability</summary><div class="atlas-setting-grid"><label>Spacing <input id="atlas-spacing" type="range" min="0.6" max="2.6" step="0.1" value="${s.spacing}"></label><label>Labels <select id="atlas-label-mode">${['smart','all','none'].map(v=>`<option ${s.labels===v?'selected':''}>${v}</option>`).join('')}</select></label><p>Click a node or line to edit. Arrowheads show source → target. Dashed patterns distinguish relationship families; provenance is shown in the inspector.</p></div></details>
 </div><aside id="atlas-inspector" class="panel direction-panel atlas-inspector">${atlasInspector()}</aside></section>
 <div class="toolbar mt12 atlas-under"><span class="hint">Your graph is editable. View changes do not alter evidence or spend tokens.</span><div class="row wrap">${btn('Rebuild','run-graph','refresh','small ghost',busy()?'disabled':'')}${btn('Import graph','import-graph','upload','small ghost')}${btn('Export graph','export-graph','download','small ghost')}</div></div>`;
};
function atlasInspector(){
 const p=state.p,g=p.graph,n=g.nodes.find(n=>n.id===state.node),e=g.edges.find(e=>e.id===state.edge),item=n||e;
 const ids=new Map(g.nodes.map(n=>[n.id,n]));
 if(!item)return `<div class="atlas-inspector-head"><span class="caps">THE GRAPH ATLAS</span><h2>Room to think.</h2><p>Select a node to shape an idea.<br>Select a connection to change the relationship.</p></div><div class="atlas-inspector-body"><div class="atlas-stat-grid"><div><strong>${fmt(g.nodes.length)}</strong><span>ideas</span></div><div><strong>${fmt(g.edges.length)}</strong><span>connections</span></div></div>${atlasState().members?`<p class="notice">Inside a cluster · ${atlasState().members.length} ideas. ${btn('Show whole graph','atlas-reset','','small')}</p>`:''}<div class="atlas-shortcuts">${btn('Add an idea','atlas-add-node','plus','primary')}${btn('Connect two ideas','atlas-connect','link','small')}</div><label class="mt20" for="direction">Your direction</label><textarea id="direction" data-brief="direction" rows="5" placeholder="The argument, question or world you are building…">${esc(p.brief.direction)}</textarea>${btn('Edit full creative brief','brief','pen','small ghost mt12')}<details class="atlas-browser mt20"><summary>Browse nodes without the canvas</summary><div>${g.nodes.slice(0,500).map(n=>`<button data-action="atlas-select" data-id="${esc(n.id)}">${esc(n.label)}</button>`).join('')}${g.nodes.length>500?'<p class="hint">Search the graph to find any of the remaining nodes.</p>':''}</div></details><div class="atlas-instruction-card"><strong>Space, not spaghetti.</strong><p>Use Clusters for the big picture, then a 1-hop neighborhood to follow a specific argument. The 2D view is always one click away.</p></div></div>`;
 const style=n?GraphScene.nodeStyle(n.kind):GraphScene.edgeStyle(e.relation),title=n?n.label:e.relation.replaceAll('_',' ');
 const sourceIds=[...new Set([...(item.source_ids||[]),...(item.evidence||[]).map(x=>x.source_id)])];
 const connections=n?g.edges.filter(x=>x.source===n.id||x.target===n.id):[];
 return `<div class="atlas-inspector-head evidence-card"><div class="row between"><span class="atlas-kind-badge" style="--node-color:${style.color}">${esc(n?n.kind:'Relationship')}</span>${ibtn('Clear selection','atlas-clear','x')}</div><h3>${esc(title)}</h3><p>${n?'Edit the idea without regenerating the graph.':esc(ids.get(e.source)?.label||e.source)+' → '+esc(ids.get(e.target)?.label||e.target)}</p></div><div class="atlas-inspector-body">
 <form id="atlas-edit-form" data-id="${esc(item.id)}" data-entity="${n?'node':'edge'}"><label for="atlas-item-label">${n?'Title':'Relationship'}</label><input id="atlas-item-label" value="${esc(n?n.label:e.relation)}" maxlength="${n?200:80}" required>${n?`<label class="mt12" for="atlas-item-kind">Node type</label><input id="atlas-item-kind" list="atlas-kinds" value="${esc(n.kind)}" maxlength="80"><datalist id="atlas-kinds">${Object.keys(GraphScene.styles).filter(k=>k!=='cluster').map(k=>`<option value="${k}">`).join('')}</datalist>`:`<p class="hint mt12">The line label and its color update when you save. The original direction remains source → target.</p>`}<label class="mt12" for="atlas-item-description">Notes / description</label><textarea id="atlas-item-description" rows="5" maxlength="${n?4000:2000}">${esc(item.description)}</textarea><div class="row wrap mt12">${btn('Save changes','atlas-save','check','primary small',busy()?'disabled':'')}${n?btn('Connect','atlas-connect','link','small'):''}</div><p id="atlas-edit-status" class="hint mt12" aria-live="polite">${esc(item.status)} · ${esc(item.id)}</p></form>
 ${n?`<div class="atlas-inspector-controls">${btn(p.brief.pinned_nodes.includes(n.id)?'Unpin':'Pin idea',p.brief.pinned_nodes.includes(n.id)?'unpin':'pin','pin','small',`data-id="${esc(n.id)}"`)}${btn('Focus neighborhood','atlas-neighbors','eye','small')}${btn('Delete node','atlas-delete','trash','small ghost danger')}</div>`:`<div class="atlas-inspector-controls">${btn('Reverse direction','atlas-reverse','refresh','small')}${btn('Delete connection','atlas-delete','trash','small ghost danger')}</div>`}
 ${sourceIds.length?`<section class="evidence-card atlas-provenance"><span class="caps">Source-file provenance</span><div class="row wrap mt12">${sourceIds.map(id=>btn(id,'atlas-source','file','small',`data-id="${esc(id)}"`)).join('')}</div>${(item.evidence||[]).slice(0,4).map(v=>`<blockquote>${esc(v.quote)}</blockquote><button class="text-link" data-action="atlas-source" data-id="${esc(v.source_id)}">Read ${esc(v.source_id)}${v.verified?' · exact passage':''}</button>`).join('')}</section>`:'<p class="hint mt20">No source anchor is attached to this item.</p>'}
 ${n?`<section class="atlas-connections"><div class="row between"><h4>Connections</h4><span class="chip">${connections.length}</span></div>${connections.slice(0,80).map(link=>{const other=link.source===n.id?link.target:link.source,f=GraphScene.edgeStyle(link.relation);return `<button data-action="atlas-edge" data-id="${esc(link.id)}" style="--link-color:${f.color}"><span>${link.source===n.id?'↗':'↙'} ${esc(link.relation.replaceAll('_',' '))}</span><strong>${esc(ids.get(other)?.label||other)}</strong></button>`;}).join('')}</section>`:''}</div>`;
}
function atlasRefreshInspector(){const el=$('#atlas-inspector');if(el){el.innerHTML=atlasInspector();atlasDirty=false;}}
const atlasPreviousDirectionRefresh=refreshDirection;
refreshDirection=function(){if(state.tab==='graph'&&$('#atlas-inspector'))atlasRefreshInspector();else atlasPreviousDirectionRefresh();};
function atlasCanLeave(){return !atlasDirty||confirm('Discard the unsaved graph form changes? Saved graph data is unchanged.');}
const atlasPreviousSelect=selectNode;
selectNode=function(id){if(!$('#atlas-inspector'))return atlasPreviousSelect(id);if(!atlasCanLeave())return;state.node=id;state.edge=null;state.path=[];drawGraph();atlasRefreshInspector();};
function atlasFit(points,s){
 const values=Object.values(points);if(!values.length)return;
 const maxX=Math.max(120,...values.map(p=>Math.abs(p.x))),maxY=Math.max(100,...values.map(p=>Math.abs(p.y)));
 s.camera.zoom=GraphScene.clamp(Math.min(470/(maxX+65),290/(maxY+65)),.08,2);s.camera.panX=0;s.camera.panY=0;
 s.camera.focal=Math.max(1600,maxX*3,maxY*3);s.fit=false;
}
function atlasShape(n,r){const shape=GraphScene.nodeStyle(n.kind).shape;if(shape==='square')return `<rect x="${-r}" y="${-r}" width="${r*2}" height="${r*2}" rx="4"/>`;if(shape==='diamond')return `<path d="M0 ${-r*1.3} ${r*1.3} 0 0 ${r*1.3} ${-r*1.3} 0Z"/>`;if(shape==='triangle')return `<path d="M0 ${-r*1.3} ${r*1.2} ${r} ${-r*1.2} ${r}Z"/>`;if(shape==='hexagon')return `<path d="M${-r} 0 ${-r*.5} ${-r} ${r*.5} ${-r} ${r} 0 ${r*.5} ${r} ${-r*.5} ${r}Z"/>`;return `<circle r="${r}"/>`;}
const atlasPreviousDraw=drawGraph;
drawGraph=function(){
 const svg=$('#graph-svg');if(!svg||!svg.classList.contains('atlas-canvas'))return atlasPreviousDraw();
 const s=atlasState(),g=state.p.graph;
 const v=GraphScene.view(g,{kind:s.kind,relation:s.relation,query:state.search,focus:s.focus?state.node:null,hops:s.focus,members:s.members,cluster:s.cluster,selected:state.node,limit:500});
 const key=JSON.stringify([v.nodes.map(n=>[n.id,n.community]),s.spacing,v.clustered]);
 if(s.key!==key){s.positions=GraphScene.layout(v,s.spacing);s.key=key;if(!s.hasLayout)s.fit=true;s.hasLayout=true;}
 if(s.fit)atlasFit(s.positions,s);
 const points=Object.create(null);for(const n of v.nodes)points[n.id]=GraphScene.project(s.positions[n.id],s.camera);
 s.view=v;s.points=points;
 const local=new Set(state.path||[]);if(state.node){local.add(state.node);for(const e of v.edges)if(e.source===state.node||e.target===state.node){local.add(e.source);local.add(e.target);}}
 const selectedEdge=v.edges.find(e=>e.id===state.edge);if(selectedEdge){local.add(selectedEdge.source);local.add(selectedEdge.target);}
 const labels=GraphScene.labelSlots(v.nodes,points,state.node,s.labels==='all');
 const edgeList=v.edges.slice().sort((a,b)=>(b.id===state.edge?1e6:local.has(b.source)&&local.has(b.target)?100:0)-(a.id===state.edge?1e6:local.has(a.source)&&local.has(a.target)?100:0)).slice(0,2000);
 const pairs=new Map();
 const lines=edgeList.map(e=>{const a=points[e.source],b=points[e.target];if(!a||!b)return '';const f=GraphScene.edgeStyle(e.relation),fi=GraphScene.families.indexOf(f),pair=JSON.stringify([e.source,e.target].sort()),index=pairs.get(pair)||0;pairs.set(pair,index+1);const bend=(index%2?-1:1)*(14+Math.floor(index/2)*22);const hi=e.id===state.edge||(state.node&&(e.source===state.node||e.target===state.node))||(state.path?.length&&state.path.includes(e.source)&&state.path.includes(e.target));const d=GraphScene.path(a,b,bend),opacity=hi?.95:local.size?.1:.40;return `<g class="atlas-edge-wrap"><path d="${d}" stroke="${f.color}" stroke-width="${hi?2.4:1.25}" stroke-dasharray="${f.dash}" stroke-opacity="${opacity}" fill="none" marker-end="url(#atlas-arrow-${fi})"/><path class="atlas-edge-hit" d="${d}" stroke="transparent" stroke-width="14" fill="none" data-edge="${esc(e.id)}" role="button" tabindex="0" aria-label="Edit relationship: ${esc(e.relation)}"><title>${esc(e.relation)} · ${esc(e.status||'clustered')} ${e.count?'· '+e.count+' connections':''}</title></path>${hi?`<text class="atlas-edge-label" x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2+bend/2-7}" fill="${f.color}" text-anchor="middle">${esc(e.relation.replaceAll('_',' '))}</text>`:''}</g>`;}).join('');
 const nodes=v.nodes.slice().sort((a,b)=>points[b.id].depth-points[a.id].depth).map(n=>{const p=points[n.id],color=GraphScene.nodeStyle(n.kind).color,sel=n.id===state.node,near=!local.size||local.has(n.id),r=n.members?19:12,scale=GraphScene.clamp(p.scale,.65,1.6);
  const showLabel=(s.labels!=='none'&&labels.has(n.id))||sel||local.has(n.id);
  const label=n.label.length>30?n.label.slice(0,28)+'…':n.label;
  return `<g class="graph-node atlas-node ${sel?'active':''}" data-node="${esc(n.id)}" data-depth="${p.depth.toFixed(2)}" transform="translate(${p.x.toFixed(2)} ${p.y.toFixed(2)})" opacity="${near?1:.30}" role="button" tabindex="0" aria-label="${esc(n.label)}"><title>${esc(n.description||n.label)}${n.members?' · click to expand':''}</title><g transform="scale(${scale})"><ellipse cy="${r+5}" rx="${r+6}" ry="5" fill="#000" opacity=".22"/><circle r="${r+13}" fill="${color}" opacity="${sel?.17:.055}"/><g fill="${color}" stroke="${sel?'#fff':color}" stroke-width="${sel?2.5:1.4}">${atlasShape(n,r)}</g><circle cx="-3" cy="-4" r="${r*.53}" fill="url(#atlas-node-light)" opacity=".65"/>${n.members?`<text text-anchor="middle" y="4" fill="#101623" font-size="10" font-weight="750">${n.members.length}</text>`:''}${state.p.brief.pinned_nodes.includes(n.id)?`<circle r="${r+7}" fill="none" stroke="${color}" stroke-dasharray="2 4"/>`:''}</g>${showLabel?`<g class="atlas-node-label"><rect x="${-Math.min(210,label.length*6.6+22)/2}" y="24" width="${Math.min(210,label.length*6.6+22)}" height="27" rx="7"/><text text-anchor="middle" y="41">${esc(label)}</text>${sel?`<text class="atlas-node-subtitle" text-anchor="middle" y="66">${esc(n.kind)} · click the inspector to edit</text>`:''}</g>`:''}</g>`;}).join('');
 svg.innerHTML=`<defs><radialGradient id="atlas-node-light" cx="30%" cy="20%"><stop stop-color="#fff" stop-opacity=".9"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>${GraphScene.families.map((f,i)=>`<marker id="atlas-arrow-${i}" viewBox="0 0 10 10" refX="19" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M1 1 9 5 1 9Z" fill="${f.color}"/></marker>`).join('')}</defs><g id="graph-world">${lines}${nodes}</g>`;
 $('#atlas-empty')?.classList.toggle('hidden',v.nodes.length>0);
 const totalEdges=g.edges.length;$('#graph-visibility').textContent=v.clustered?`${v.nodes.length} clusters · all ${v.matched} matching ideas represented`:`${v.nodes.length} of ${g.nodes.length} ideas · ${edgeList.length} of ${totalEdges} connections${v.hidden?' · '+v.hidden+' more — search, filter or use Clusters':''}`;
 $('#atlas-hint').textContent=s.camera.flat?'Drag to pan · drag nodes to arrange · scroll to zoom':'Drag to orbit · Shift-drag to pan · scroll to zoom';
 $$('[data-action="atlas-3d"]').forEach(e=>e.setAttribute('aria-pressed',String(!s.camera.flat)));$$('[data-action="atlas-2d"]').forEach(e=>e.setAttribute('aria-pressed',String(s.camera.flat)));
 const mini=$('#atlas-minimap');if(mini){const radius=Math.max(240,...Object.values(s.positions).map(p=>Math.max(Math.abs(p.x),Math.abs(p.y))));s.mapRadius=radius;mini.innerHTML=`<span>OVERVIEW</span><svg viewBox="0 0 160 100" role="img" aria-label="Click to recenter the graph">${v.nodes.map(n=>{const p=s.positions[n.id];return `<circle cx="${80+p.x/radius*65}" cy="${50+p.y/radius*38}" r="${n.id===state.node?3:1.5}" fill="${GraphScene.nodeStyle(n.kind).color}"/>`;}).join('')}<rect x="${GraphScene.clamp(39-s.camera.panX/15,2,108)}" y="${GraphScene.clamp(24-s.camera.panY/15,2,68)}" width="${GraphScene.clamp(80/s.camera.zoom,20,154)}" height="${GraphScene.clamp(47/s.camera.zoom,15,94)}" fill="none" stroke="#a4b6ff" stroke-opacity=".55" rx="4"/></svg>`;}
 atlasAttach(svg);
};
function atlasAttach(svg){
 if(svg.dataset.bound)return;svg.dataset.bound='1';let drag=null;
 const point=ev=>{const p=svg.createSVGPoint();p.x=ev.clientX;p.y=ev.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());};
 svg.addEventListener('pointerdown',ev=>{if(ev.button>1)return;const p=point(ev),node=ev.target.closest('[data-node]');drag={start:p,last:p,id:node?.dataset.node,shift:ev.shiftKey||ev.button===1,moved:false};svg.setPointerCapture(ev.pointerId);});
 svg.addEventListener('pointermove',ev=>{if(!drag)return;const p=point(ev),s=atlasState();if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>4)drag.moved=true;if(!drag.moved)return;const dx=p.x-drag.last.x,dy=p.y-drag.last.y;drag.last=p;if(drag.id&&s.positions[drag.id]){const position=s.positions[drag.id],d=GraphScene.dragDelta(dx,dy,position,s.camera);position.x+=d.x;position.y+=d.y;position.z+=d.z;}else if(drag.shift||s.camera.flat){s.camera.panX+=dx;s.camera.panY+=dy;}else{s.camera.yaw+=dx*.006;s.camera.pitch=GraphScene.clamp(s.camera.pitch+dy*.006,-1.25,1.25);}atlasSchedule();});
 svg.addEventListener('pointerup',ev=>{if(!drag)return;const d=drag;drag=null;if(svg.hasPointerCapture(ev.pointerId))svg.releasePointerCapture(ev.pointerId);if(d.moved){atlasPersist();return;}const target=document.elementFromPoint(ev.clientX,ev.clientY),node=target?.closest('[data-node]'),edge=target?.closest('[data-edge]');if(node)atlasPick(node.dataset.node);else if(edge){if(atlasState().view.clustered){toast('Expand a cluster to edit individual connections.');return;}if(!atlasCanLeave())return;state.edge=edge.dataset.edge;state.node=null;drawGraph();atlasRefreshInspector();}});
 svg.addEventListener('pointercancel',()=>{drag=null;});
 svg.addEventListener('wheel',ev=>{ev.preventDefault();const s=atlasState(),p=point(ev),old=s.camera.zoom;const zoom=GraphScene.clamp(old*Math.exp(-ev.deltaY*.0013),.08,8);s.camera.panX=(p.x-550)-(p.x-550-s.camera.panX)*zoom/old;s.camera.panY=(p.y-360)-(p.y-360-s.camera.panY)*zoom/old;s.camera.zoom=zoom;atlasSchedule();atlasPersist();},{passive:false});
 svg.addEventListener('keydown',ev=>{const n=ev.target.closest('[data-node]'),e=ev.target.closest('[data-edge]');if(['Enter',' '].includes(ev.key)&&(n||e)){ev.preventDefault();ev.stopPropagation();if(n)atlasPick(n.dataset.node);else{if(atlasState().view.clustered){toast('Expand a cluster to edit individual connections.');return;}if(!atlasCanLeave())return;state.edge=e.dataset.edge;state.node=null;drawGraph();atlasRefreshInspector();}return;}const s=atlasState();if(['+','=','-','f','F','2','3','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();if(ev.key==='2')s.camera.flat=true;else if(ev.key==='3')s.camera.flat=false;else if(ev.key.toLowerCase()==='f')s.fit=true;else if(ev.key==='+'||ev.key==='=')s.camera.zoom=GraphScene.clamp(s.camera.zoom*1.2,.08,8);else if(ev.key==='-')s.camera.zoom=GraphScene.clamp(s.camera.zoom/1.2,.08,8);else if(ev.key==='ArrowLeft')s.camera.yaw-=.12;else if(ev.key==='ArrowRight')s.camera.yaw+=.12;else if(ev.key==='ArrowUp')s.camera.pitch-=.1;else if(ev.key==='ArrowDown')s.camera.pitch+=.1;atlasSchedule();atlasPersist();}});
}
function atlasPick(id){const s=atlasState(),n=s.view?.nodes.find(n=>n.id===id);if(n?.members){if(!atlasCanLeave())return;s.members=n.members;s.cluster=false;s.fit=true;state.node=null;state.edge=null;render();return;}selectNode(id);}
async function atlasEdit(operation,id,values){
 if(!editable())return;await flush();const pid=state.p.id,version=state.p.version;
 const p=await api('/projects/'+pid+'/graph/edit',{version,operation,...(id?{id}:{}),...(values?{values}:{})});
 if(state.p?.id!==pid)return;state.p=p;atlasDirty=false;syncSummary();updateSaved('Saved locally');return p;
}
function atlasConnectDialog(){const nodes=state.p.graph.nodes;if(nodes.length<2){toast('Add at least two ideas before connecting them.');return;}const options=current=>nodes.map(n=>`<option value="${esc(n.id)}" ${current===n.id?'selected':''}>${esc(n.label)}</option>`).join('');showModal('Connect ideas','A manual relationship is saved as proposed. Original sources stay unchanged.',`<div class="form-grid"><div><label for="atlas-from">From</label><select id="atlas-from">${options(state.node||nodes[0].id)}</select></div><div><label for="atlas-to">To</label><select id="atlas-to">${options(nodes.find(n=>n.id!==state.node)?.id||nodes[1].id)}</select></div><div class="form-full"><label for="atlas-link-relation">Relationship</label><input id="atlas-link-relation" value="supports" list="atlas-relations" maxlength="80"><datalist id="atlas-relations">${['supports','contradicts','cites','leads_to','questions','influences_style','related_to'].map(x=>`<option value="${x}">`).join('')}</datalist></div><div class="form-full"><label for="atlas-link-notes">Notes</label><textarea id="atlas-link-notes" rows="3"></textarea></div></div>`,btn('Save connection','atlas-create-edge','link','primary'));}
const atlasPreviousAction=handleAction;
handleAction=async function(el){
 const action=el.dataset.action;
 if(['zoom-in','zoom-out','fit-graph'].includes(action)&&$('#atlas-inspector')){const s=atlasState();if(action==='fit-graph')s.fit=true;else s.camera.zoom=GraphScene.clamp(s.camera.zoom*(action==='zoom-in'?1.25:.8),.08,8);drawGraph();atlasPersist();return;}
 if(!action.startsWith('atlas-')){if(atlasDirty&&['tab','home','open-project','new','run-graph','run-angles','import-graph','theme'].includes(action)){if(!atlasCanLeave())return;atlasDirty=false;}return atlasPreviousAction(el);}
 const s=atlasState();
 switch(action){
 case 'atlas-2d':case 'atlas-3d':s.camera.flat=action==='atlas-2d';s.fit=true;drawGraph();atlasPersist();break;
 case 'atlas-expand':s.expanded=!s.expanded;$('.atlas-shell').classList.toggle('atlas-expanded',s.expanded);break;
 case 'atlas-clusters':if(!atlasCanLeave())return;s.cluster=!s.cluster;s.members=null;s.focus=0;s.fit=true;state.node=null;state.edge=null;render();break;
 case 'atlas-reset':if(!atlasCanLeave())return;s.kind='';s.relation='';s.focus=0;s.members=null;s.cluster=state.p.graph.nodes.length>160;s.fit=true;s.camera.yaw=.18;s.camera.pitch=-.13;state.search='';state.node=null;state.edge=null;state.path=[];render();break;
 case 'atlas-clear':if(!atlasCanLeave())return;state.node=null;state.edge=null;s.focus=0;drawGraph();atlasRefreshInspector();break;
 case 'atlas-select':if(!atlasCanLeave())return;atlasDirty=false;s.members=null;s.kind='';s.relation='';state.search='';s.cluster=false;s.focus=1;s.fit=true;state.node=el.dataset.id;state.edge=null;render();break;
 case 'atlas-edge':if(!atlasCanLeave())return;state.edge=el.dataset.id;state.node=null;drawGraph();atlasRefreshInspector();break;
 case 'atlas-neighbors':if(!atlasCanLeave())return;s.focus=1;s.cluster=false;s.fit=true;render();break;
 case 'atlas-source':sourceDialog(el.dataset.id);break;
 case 'atlas-save':{const form=$('#atlas-edit-form'),node=form.dataset.entity==='node',values=node?{label:$('#atlas-item-label').value,kind:$('#atlas-item-kind').value,description:$('#atlas-item-description').value}:{relation:$('#atlas-item-label').value,description:$('#atlas-item-description').value};if(await atlasEdit(form.dataset.entity+'.update',form.dataset.id,values)){render();toast('Graph edit saved. Original source passages are unchanged.');}break;}
 case 'atlas-add-node':if(!editable()||!atlasCanLeave())return;showModal('Add an idea','An editable node, not a new model request.',`<label for="atlas-new-label">Title</label><input id="atlas-new-label" maxlength="200" style="width:100%"><label for="atlas-new-kind" class="mt12">Type</label><select id="atlas-new-kind">${['concept','claim','source','evidence','theme','character','event','question','tension','canon'].map(k=>`<option>${k}</option>`).join('')}</select><label for="atlas-new-notes" class="mt12">Notes</label><textarea id="atlas-new-notes" rows="4"></textarea>`,btn('Add node','atlas-create-node','plus','primary'));break;
 case 'atlas-create-node':{const p=await atlasEdit('node.add',null,{label:$('#atlas-new-label').value,kind:$('#atlas-new-kind').value,description:$('#atlas-new-notes').value});if(p){state.node=p.graph.nodes.at(-1).id;state.edge=null;s.cluster=false;s.members=null;s.fit=true;closeModal();render();}break;}
 case 'atlas-connect':if(editable()&&atlasCanLeave())atlasConnectDialog();break;
 case 'atlas-create-edge':{const p=await atlasEdit('edge.add',null,{source:$('#atlas-from').value,target:$('#atlas-to').value,relation:$('#atlas-link-relation').value,description:$('#atlas-link-notes').value});if(p){state.edge=p.graph.edges.at(-1).id;state.node=null;closeModal();render();}break;}
 case 'atlas-reverse':{const e=state.p.graph.edges.find(e=>e.id===state.edge);if(e&&await atlasEdit('edge.update',e.id,{source:e.target,target:e.source}))render();break;}
 case 'atlas-delete':{const node=!!state.node,id=state.node||state.edge;if(!confirm(node?'Delete this node and its attached connections? Your sources and manuscript stay intact. Undo is available.':'Delete this connection? Undo is available.'))return;if(await atlasEdit(node?'node.delete':'edge.delete',id)){state.node=null;state.edge=null;render();}break;}
 case 'atlas-undo':{if(!editable()||!atlasCanLeave())return;await flush();const pid=state.p.id,p=await api('/projects/'+pid+'/graph/undo',{version:state.p.version});if(state.p?.id===pid){state.p=p;state.node=null;state.edge=null;atlasDirty=false;s.key='';s.fit=true;syncSummary();render();toast('Last graph edit undone.');}break;}
 }
};
document.addEventListener('change',ev=>{if(!state.p)return;const s=atlasState(),id=ev.target.id;if(id==='atlas-kind'){s.kind=ev.target.value;s.fit=true;}else if(id==='atlas-relation'){s.relation=ev.target.value;s.fit=true;}else if(id==='atlas-focus'){s.focus=Number(ev.target.value);if(s.focus&&!state.node){toast('Select an idea first, then choose its neighborhood.');s.focus=0;ev.target.value='0';}s.cluster=false;s.fit=true;}else if(id==='atlas-label-mode')s.labels=ev.target.value;else return;drawGraph();});
document.addEventListener('input',ev=>{if(ev.target.closest?.('#atlas-edit-form')){atlasDirty=true;$('#atlas-edit-status').textContent='Unsaved graph changes';}if(ev.target.id==='atlas-spacing'){const s=atlasState();s.spacing=Number(ev.target.value);atlasSchedule();atlasPersist();}});
document.addEventListener('submit',ev=>{if(ev.target.id==='atlas-edit-form'){ev.preventDefault();handleAction($('[data-action="atlas-save"]',ev.target)).catch(e=>toast(e.message,true));}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&$('.atlas-expanded')&&!$('.modal')){$('.atlas-expanded').classList.remove('atlas-expanded');atlasState().expanded=false;}});
document.addEventListener('click',ev=>{if(ev.target.closest?.('#atlas-minimap')){atlasState().fit=true;drawGraph();}});
const atlasPreviousRender=render;
render=function(){cancelAnimationFrame(atlasFrame);atlasFrame=0;atlasPreviousRender();if(state.p&&state.tab==='graph')atlasSchedule();const mark=$('.brand img');if(mark)mark.src='/static/atlas-mark.svg';};
if(state.p||state.projects.length)render();
