/* Authorial intent is not an evidence slider. Four modes, including existing projects. */
'use strict';
const writingModeNames={nonfiction:'Nonfiction',fiction:'Fiction',science:'Science',polemic:'Polemic'};
const editorialUI={statusKey:'',pendingKey:''};
const polemicPreviousNew=newDialog;
newDialog=function(mode='nonfiction'){polemicPreviousNew(mode);$('#project-mode').insertAdjacentHTML('beforeend','<option value="polemic">Polemic — argument, satire & opinion</option>');if(mode==='polemic')$('#project-mode').value='polemic';};
const polemicPreviousWelcome=welcomeHTML;
welcomeHTML=function(){return polemicPreviousWelcome().replace('</div><div class="welcome-end">',`<button class="panel welcome-card" data-action="new" data-mode="polemic">${icon('pen')}<h3>Make your argument.</h3><p>Polemic, satire and opinion. Keep the thesis, the wit and the bite. Check the facts without flattening the position.</p></button></div><div class="welcome-end">`);};
const polemicPreviousBrief=briefDialog;
briefDialog=function(){polemicPreviousBrief();const b=state.p.brief;$('.modal-body .form-grid').insertAdjacentHTML('afterbegin',`<section class="form-full argument-controls"><div class="row between wrap"><h3>Your argument</h3><span class="chip green">${esc(writingModeNames[state.p.mode])}</span></div><label class="mt12" for="b-thesis">Core thesis / position to preserve</label><textarea id="b-thesis" rows="4" maxlength="8000" placeholder="What should this piece argue—not merely discuss? Leave blank to use your direction.">${esc(b.thesis||'')}</textarea><div class="form-grid mt12"><div><label for="b-stance_policy">Writing purpose</label><select id="b-stance_policy" ${state.p.mode==='polemic'?'disabled':''}>${[['auto','Follow the brief'],['preserve','Develop and defend my position'],['explore','Investigate an open question']].map(([v,l])=>`<option value="${v}" ${(state.p.mode==='polemic'?'preserve':b.stance_policy||'auto')===v?'selected':''}>${l}</option>`).join('')}</select></div><div><label for="b-rhetorical_force">Rhetorical force · ${b.rhetorical_force??70}%</label><input id="b-rhetorical_force" type="range" min="0" max="100" value="${b.rhetorical_force??70}"><p class="hint">Controlled → pointed → uncompromising. Not a factual-certainty dial.</p></div></div><p class="hint mt12">Polemic keeps your position. Nonfiction can also argue a case. Your author voice now informs angle discovery and outlining, not just the final prose. No mode invents evidence.</p></section>`);};
const polemicPreviousDirection=directionHTML;
directionHTML=function(){let value=polemicPreviousDirection();if(!state.p)return value;const b=state.p.brief;if(state.p.mode==='polemic'||b.stance_policy==='preserve')value=value.replace('What should this piece explore?','What should this piece argue?');const block=`<section class="argument-direction mt20"><div class="range-row"><label for="rhetorical_force">Rhetorical force</label><span id="rhetorical_force-value">${b.rhetorical_force??70}%</span></div><input id="rhetorical_force" type="range" min="0" max="100" data-brief="rhetorical_force" value="${b.rhetorical_force??70}" ${busy()?'disabled':''}><div class="range-ends"><span>Understated</span><span>Uncompromising</span></div><p class="hint mt12">Evidence detail controls the treatment of sources—not your right to take a position. Factual precision and rhetorical force are separate.</p>${b.thesis?`<p class="hint mt12"><strong>Core thesis:</strong> ${esc(b.thesis)}</p>`:''}${btn('Edit thesis & purpose','brief','pen','small ghost')}</section>`;return value.replace(/<\/div><\/aside>$/,block+'</div></aside>');};
function modeDialog(){const p=state.p;showModal('Writing mode','Change the job of the writer—not your stored material.',`<label for="writing-mode">Mode for this project</label><select id="writing-mode" style="width:100%">${Object.entries(writingModeNames).map(([k,l])=>`<option value="${k}" ${p.mode===k?'selected':''}>${l}</option>`).join('')}</select><div class="notice">Your sources, graph, voice profile, angles, outline and manuscript stay in this project. Polemic develops your stated argument rather than proposing a neutral substitute. Existing generated angles are not automatically rewritten: refresh angles afterward using the current graph.</div>`,btn('Apply writing mode','apply-writing-mode','check','primary'));}
function paintEditorialStatus(status){const p=state.p;if(!p||p.mode==='science')return;$('#editorial-status')?.remove();const body=$('.workspace-body');if(!body)return;const view=state.tab;const stale=view==='angles'?status.angles_stale:view==='outline'?status.outline_stale:false;const samples=status.voice_enabled?`Voice: ${status.voice_samples} sample${status.voice_samples===1?'':'s'}`:'Author voice is switched off';const message=stale?(view==='angles'?'These saved angles predate the current brief, mode or voice. Refresh them here—no graph rebuild needed.':'This outline predates your current argument or voice. Keep it deliberately, edit it, or regenerate it.'):(p.mode==='polemic'?'Argument-led writing. Your thesis and voice guide every editorial stage.':'Your brief determines whether to argue or explore; factual checking does not require a middle position.');const node=document.createElement('div');node.id='editorial-status';node.className='editorial-status';node.innerHTML=`<div class="spacer"><span class="caps">${esc(writingModeNames[p.mode])} · ${samples}</span><p>${esc(message)}</p></div><div class="row wrap">${view==='angles'&&stale?btn('Refresh angles with my voice','run-angles','refresh','small',busy()?'disabled':''):''}${p.mode==='nonfiction'?btn('Switch to Polemic','choose-polemic','pen','small'):''}${view==='outline'&&stale?btn('Regenerate outline','run-outline','list','small',busy()?'disabled':''):''}</div>`;body.prepend(node);}
const polemicPreviousRender=render;
render=function(){if(state.p&&state.p.mode!=='science'&&state.tab==='research')state.tab='sources';polemicPreviousRender();const p=state.p;if(!p)return;const header=$('.workspace-head .header-actions');header?.insertAdjacentHTML('afterbegin',btn(writingModeNames[p.mode]+' · Change','writing-mode','pen','small ghost'));if(p.mode==='polemic'){const desc=$('.workspace-head .description');if(desc)desc.textContent='Develop your argument in your voice. Precision is not compulsory compromise.';const crumb=$('.breadcrumb');if(crumb)crumb.innerHTML='Studio <span>/</span> Polemic';const title=$('.workspace-head h1');if(title)title.textContent={sources:'Give your argument its material.',graph:'Find the sharpest route to your argument.',angles:'Different angles. Your position.',outline:'Make the argument land.',write:'Write it like you mean it.'}[state.tab]||'Make your argument.';}
 const key=p.id+':'+p.version;if(editorialUI.statusKey===key&&editorialUI.status){paintEditorialStatus(editorialUI.status);return;}if(editorialUI.pendingKey===key)return;editorialUI.pendingKey=key;api('/projects/'+p.id+'/editorial/status').then(status=>{if(state.p?.id===p.id&&state.p.version===status.version){editorialUI.status=status;editorialUI.statusKey=key;paintEditorialStatus(status);}}).catch(()=>{}).finally(()=>{if(editorialUI.pendingKey===key)editorialUI.pendingKey='';});};
const polemicPreviousReview=reviewHTML;
reviewHTML=function(){let value=polemicPreviousReview();const a=state.p?.review?.authorial_assessment;if(a&&Object.keys(a).length)value+=`<div class="evidence-card mt20"><span class="caps">Authorial fidelity</span><p class="hint mt12">${esc(a.summary||'The editor assessed the intended argument separately from factual support.')}</p><div class="row wrap mt12">${[['intent_preserved','Purpose'],['stance_preserved','Position'],['voice_preserved','Voice']].filter(([k])=>typeof a[k]==='boolean').map(([k,label])=>`<span class="chip ${a[k]?'green':'gold'}">${label}: ${a[k]?'preserved':'needs attention'}</span>`).join('')}</div></div>`;return value;};
const polemicPreviousAction=handleAction;
handleAction=async function(el){const a=el.dataset.action;if(a==='writing-mode'||a==='choose-polemic'){if(!editable())return;await flush();modeDialog();if(a==='choose-polemic')$('#writing-mode').value='polemic';return;}if(a==='apply-writing-mode'){await flush();const mode=$('#writing-mode').value;state.p=await api('/projects/'+state.p.id+'/writing-mode',{mode,version:state.p.version});syncSummary();editorialUI.statusKey='';closeModal();render();toast('Writing mode changed. Your existing work is preserved.');return;}if(a==='save-brief'&&$('#b-thesis')){const force=Number($('#b-rhetorical_force').value);if(!Number.isInteger(force)||force<0||force>100)throw new Error('Choose rhetorical force between 0 and 100.');state.p.brief={...state.p.brief,thesis:$('#b-thesis').value,stance_policy:state.p.mode==='polemic'?'preserve':$('#b-stance_policy').value,rhetorical_force:force};}return polemicPreviousAction(el);};
document.addEventListener('input',event=>{if(event.target.id==='b-rhetorical_force')$('label[for="b-rhetorical_force"]').textContent='Rhetorical force · '+event.target.value+'%';});
if(state.p||state.projects.length)render();
