/* GraphPaper 0.2: author voice, project inbox, reversible prose tools and Codex sign-in. */
'use strict';
const studio = {syncing:false,discovery:[],audit:null};
const priorSourcesHTML = sourcesHTML;
sourcesHTML = function(){return `<div class="studio-strip"><div><strong>Your material. Your voice.</strong><p>Keep files together and let your own writing guide the result.</p></div><div class="row wrap">${btn('Your writing voice','studio-voice','pen','small')}${btn('Project folder','studio-folder','folder','small')}</div></div>`+priorSourcesHTML();};
const priorWriteHTML = writeHTML;
writeHTML = function(){let html=priorWriteHTML();const tools=`<div class="studio-tools"><span class="caps">Prose craft</span><div class="row wrap mt12">${btn('Humanize','studio-polish','','small',busy()?'disabled':'')}${btn('Deslop','studio-deslop','','small',busy()?'disabled':'')}${btn('Inspect prose','studio-audit','search','small ghost')}</div>${state.p.polish?btn('Compare proposed edit','studio-compare','branch','primary mt12'):''}<button class="text-link mt12" data-action="studio-voice">${esc(state.p.voice_profile?.enabled?'Using your voice settings':'Voice matching is off')} · edit</button></div>`;return html.replace('<div class="stack">',tools+'<div class="stack">');};
const priorSettingsForm = settingsForm;
settingsForm = function(){let html=priorSettingsForm();html=html.replace('<select id="s-provider">',`<select id="s-provider"><option value="codex" ${state.settings.provider==='codex'?'selected':''}>Codex — sign in with ChatGPT (no API key)</option>`);return `<div class="studio-auth"><div class="row between wrap"><div><h3>Use your ChatGPT account</h3><p>Codex subscription access, with browser sign-in.</p></div><span class="chip">No writing API key</span></div><div class="row wrap mt12">${btn('Sign in with ChatGPT','studio-codex-login','lock','primary small')}${btn('Check sign-in','studio-codex-status','refresh','small')}${btn('Sign out','studio-codex-logout','','small ghost')}</div><p id="codex-status" class="hint mt12">The Windows release includes the official Codex runtime. Sign-in and credential storage are handled by Codex in a separate GraphPaper account directory. JEV remains an optional, separate connection.</p><details class="mt12"><summary>Existing Codex runtime</summary><label class="mt12" for="s-codex_executable">Native executable (leave blank for bundled/auto-detected)</label><input id="s-codex_executable" value="${esc(state.settings.codex_executable||'')}" placeholder="C:\\…\\codex.exe" style="width:100%"></details></div>`+html;};
const priorSaveSettings = saveSettings;
saveSettings = async function(){if($('#s-codex_executable'))state.settings.codex_executable=$('#s-codex_executable').value.trim();return priorSaveSettings();};
function voiceDialog(){const p=state.p,v=p.voice_profile,examples=p.sources.filter(s=>s.role==='voice'&&s.enabled);showModal('Your writing voice','Learn from your own articles, then keep the profile under your control.',`<div class="studio-sample-actions row wrap">${btn('Upload samples','studio-upload-voice','upload','small')}${btn('Paste a sample','studio-paste-voice','file','small')}${btn('Find my writing online','studio-author-web','link','small')}</div><div class="studio-samples mt20">${examples.length?examples.map(s=>`<div class="studio-sample"><span>${icon('file')}</span><div class="spacer"><strong>${esc(s.title)}</strong><small>${esc(s.id)} · ${fmt(words(s.text))} words${s.url?' · web source':''}</small></div>${ibtn('Read sample','source','eye',`data-id="${esc(s.id)}"`)}</div>`).join(''):'<p class="hint">Add pieces you wrote. A few representative articles or chapters work better than isolated slogans.</p>'}</div><div class="row wrap mt20">${btn(v.learned_at?'Relearn from samples':'Learn my writing style','studio-learn-voice','spark','primary',busy()?'disabled':'')}<span class="hint">One analysis request. The profile is used for new drafts and revisions.</span></div><div class="form-grid mt20"><div><label for="voice-name">Profile name</label><input id="voice-name" value="${esc(v.name)}"></div><div><label for="voice-strength">Voice influence: <span id="voice-strength-value">${v.strength}</span>%</label><input id="voice-strength" type="range" min="0" max="100" value="${v.strength}"></div><div class="form-full"><label for="voice-instructions">Editable style instructions</label><textarea id="voice-instructions" rows="9" placeholder="Learn from your samples or write your own style instructions here.">${esc(v.instructions)}</textarea></div><label class="checkbox-row form-full"><input id="voice-enabled" type="checkbox" ${v.enabled?'checked':''}><span>Use this voice for drafting, revision and humanizing.</span></label></div>${v.metrics?.words?`<div class="studio-metrics"><span><strong>${fmt(v.metrics.words)}</strong> sample words</span><span><strong>${v.metrics.mean_sentence_words}</strong> words / sentence</span><span><strong>${v.metrics.sentence_variation}</strong> sentence variation</span></div>`:''}${v.observations?.length?`<details class="mt12"><summary>What the profile noticed</summary>${v.observations.map(x=>`<p class="hint mt12">${esc(x)}</p>`).join('')}</details>`:''}<div class="notice">Samples guide rhythm, diction and rhetorical choices. They are never cited as facts or copied into the new piece. This is reusable prompting, not model fine-tuning. Changing samples makes the learned profile stale until you relearn it.</div>`,btn('Save voice settings','studio-save-voice','check','primary'),true);}
function authorWebDialog(){showModal('Find your writing online','Enter an article, blog archive or author page. Choose what belongs in your voice library.',`<label for="author-url">Your article or author-page URL</label><div class="row"><input id="author-url" type="url" placeholder="https://your-site.example/blog" class="spacer">${btn('Find articles','studio-discover','search','small')}</div><div id="author-results" class="mt20"></div><p class="hint mt12">Only linked pages on the same site are listed. This does not verify authorship; select your own work, not other contributors, navigation pages or quotations.</p>`,btn('Import selected samples','studio-import-authors','plus','primary','disabled'),true);}
async function folderDialog(){await flush();const info=await api('/projects/'+state.p.id+'/workspace');showModal('This project’s folder','Drop documents into its Inbox. They become part of this project automatically.',`<label>Project location</label><input class="studio-path" readonly value="${esc(info.path)}" aria-label="Project folder path"><div class="row wrap mt12">${btn('Open folder','studio-open-folder','folder','primary small')}${btn('Import files now','studio-scan-folder','refresh','small')}</div><div class="studio-folder-grid mt20"><div><strong>Inbox / Evidence</strong><p>Citable research and source articles.</p></div><div><strong>Inbox / Voice</strong><p>Your writing samples.</p></div><div><strong>Inbox / Canon</strong><p>Established characters, events and world rules.</p></div><div><strong>Inbox / Inspiration</strong><p>Possibilities, not factual evidence.</p></div></div><label class="checkbox-row mt20"><input id="folder-auto" type="checkbox" ${state.p.auto_import?'checked':''}><span>Automatically check the Inbox while this project is open and idle. Files added while the app is closed are picked up on the next visit.</span></label><div id="folder-events" class="mt12"></div><div class="notice">Local import makes no AI calls. Original app uploads are kept in Originals. Removed inbox files do not erase sources; deleting the project does not delete this folder. SQLite remains the project’s saved state.</div>`,btn('Save preference','studio-save-folder','check','primary'),true);}
function polishDialog(mode){showModal(mode==='deslop'?'Remove the slop':'Make it sound like you','A proposed edit is saved separately. Your current draft stays untouched.',`<label for="craft-instruction">Optional editorial direction</label><textarea id="craft-instruction" rows="4" placeholder="Keep my dry humor. Remove repeated conclusions, but preserve the technical qualifications."></textarea><label class="mt12" for="craft-mode">Editing pass</label><select id="craft-mode"><option value="humanize" ${mode==='humanize'?'selected':''}>Humanize — rhythm, voice and natural expression</option><option value="deslop" ${mode==='deslop'?'selected':''}>Deslop — filler, redundancy and formulaic phrasing</option><option value="both">Both in one pass</option></select><div class="notice">Quotations, numbers, citations, links and code are protected. A second model check looks for meaning drift. You compare the result before accepting it. No invented experiences, random mistakes or AI-detector-evasion tricks.</div>`,btn('Create proposed edit','studio-run-craft','pen','primary'));}
async function auditDialog(){await flush();const audit=await api('/projects/'+state.p.id+'/craft/audit',{});studio.audit=audit;showModal('Prose inspection','Local checks only. No model request and no changes to your draft.',`<div class="studio-metrics"><span><strong>${audit.count}</strong> editorial cues</span><span><strong>${audit.metrics.mean_sentence_words}</strong> words / sentence</span><span><strong>${audit.metrics.sentence_variation}</strong> sentence variation</span></div>${audit.findings.map(f=>`<div class="review-issue"><span class="severity">${esc(f.rule)}</span><blockquote>${esc(f.excerpt)}</blockquote><p>${esc(f.suggestion)}</p></div>`).join('')||'<p class="hint mt20">No listed phrase patterns were found. This is not a certificate of good prose.</p>'}${audit.repeated_openings.length?`<p class="hint mt20">Repeated paragraph openings: ${audit.repeated_openings.map(esc).join('; ')}</p>`:''}<div class="notice">${esc(audit.note)}</div>`,btn('Humanize','studio-polish','pen','small')+btn('Deslop','studio-deslop','pen','primary small'),true);}
function compareDialog(){const c=state.p.polish;if(!c){toast('No proposed prose edit yet.');return;}showModal('Original and proposed edit','Read the changes. The original remains your current draft until you accept.',`<div class="studio-edit-summary"><strong>${esc(c.review.summary||'Proposed '+c.mode+' edit')}</strong><p>${c.before.count} → ${c.after.count} listed cues · ${c.protected_spans} protected spans kept intact</p></div>${(c.review.warnings||[]).map(x=>`<div class="notice">${esc(x)}</div>`).join('')}<div class="studio-compare"><section><h3>Original</h3><article class="prose">${markdown(state.p.draft)}</article></section><section><h3>Proposed</h3><article class="prose">${markdown(c.draft)}</article></section></div><details class="mt20"><summary>Line-by-line changes</summary><pre class="studio-diff">${c.diff.map(l=>`<span class="${l.startsWith('+')?'addition':l.startsWith('-')?'deletion':''}">${esc(l)}</span>`).join('\n')}</pre></details>${!c.review.meaning_preserved?'<label class="checkbox-row mt20"><input id="craft-ack" type="checkbox"><span>The reviewer flagged possible meaning changes. I have checked the comparison and still want to apply this edit.</span></label>':''}`,btn('Discard proposal','studio-discard-craft','x','ghost')+btn('Accept this edit','studio-accept-craft','check','primary'),true);}
async function scanFolder(force=false){if(studio.syncing||busy()||!state.p)return;await flush();studio.syncing=true;const id=state.p.id,version=state.p.version;try{const result=await api('/projects/'+id+'/workspace/scan',{force});if(state.p?.id!==id)return result;if(result.changed&&state.p.version===version){const edits={...pending};state.p=result.project;Object.assign(state.p,edits);syncSummary();if(!Object.keys(edits).length&&!$('.modal'))render();}if(force&&$('#folder-events'))$('#folder-events').innerHTML=result.events.map(e=>`<p class="hint">${esc(e.path)} · ${esc(e.status)}${e.message?' — '+esc(e.message):''}</p>`).join('')||'<p class="hint">Inbox is up to date. No new files to import.</p>';else if(result.changed)toast(`${result.events.filter(e=>['imported','updated'].includes(e.status)).length} inbox file(s) added or updated.`);return result;}finally{studio.syncing=false;}}
const priorHandleAction=handleAction;
handleAction=async function(el){const action=el.dataset.action;if(!action.startsWith('studio-'))return priorHandleAction(el);switch(action){
 case 'studio-voice':await flush();voiceDialog();break;
 case 'studio-upload-voice':if(!editable())return;chooseFile('.pdf,.docx,.txt,.md,.html,.htm',true,async files=>{await flush();for(const file of files){if(file.size>20*1024*1024)throw new Error('Each sample must be under 20 MB.');const form=new FormData();form.append('file',file);form.append('role','voice');state.p=await api('/projects/'+state.p.id+'/sources/file',form);}syncSummary();render();voiceDialog();toast('Writing samples added.');});break;
 case 'studio-paste-voice':if(editable()){pasteDialog();$('#source-role').value='voice';}break;
 case 'studio-author-web':authorWebDialog();break;
 case 'studio-discover':el.disabled=true;try{$('#modal-status').textContent='Finding linked articles…';const r=await api('/voice/discover',{url:$('#author-url').value});studio.discovery=r.pages;$('#author-results').innerHTML=r.pages.map((p,i)=>`<label class="checkbox-row"><input class="author-page" type="checkbox" value="${i}"><span><strong>${esc(p.title)}</strong><small class="studio-url">${esc(p.url)}</small></span></label>`).join('');$('#modal-status').textContent=r.note;$('[data-action="studio-import-authors"]').disabled=false;}finally{el.disabled=false;}break;
 case 'studio-import-authors':{const pages=$$('.author-page:checked').map(x=>studio.discovery[Number(x.value)]);if(!pages.length||pages.length>12)throw new Error('Select between 1 and 12 writing samples.');el.disabled=true;await flush();const errors=[];try{for(let i=0;i<pages.length;i++){$('#modal-status').textContent=`Importing sample ${i+1}/${pages.length}…`;try{state.p=await api('/projects/'+state.p.id+'/sources/url',{url:pages[i].url,role:'voice'});}catch(e){errors.push(pages[i].title+': '+e.message);}}syncSummary();render();voiceDialog();if(errors.length)toast(errors.join(' '),true);else toast('Selected writing samples imported.');}finally{el.disabled=false;}break;}
 case 'studio-learn-voice':closeModal();await startJob('voice');break;
 case 'studio-save-voice':{if(!editable())return;const v={...state.p.voice_profile,name:$('#voice-name').value,instructions:$('#voice-instructions').value,strength:Number($('#voice-strength').value),enabled:$('#voice-enabled').checked};if(v.instructions!==state.p.voice_profile.instructions)v.sample_hash='';state.p.voice_profile=v;queueSave({voice_profile:v});await flush();closeModal();render();toast('Voice settings saved.');break;}
 case 'studio-folder':await folderDialog();break;
 case 'studio-open-folder':{const r=await api('/projects/'+state.p.id+'/workspace/open',{});if(!r.opened)toast('Open this folder in your file manager: '+r.path);break;}
 case 'studio-scan-folder':await scanFolder(true);break;
 case 'studio-save-folder':state.p.auto_import=$('#folder-auto').checked;queueSave({auto_import:state.p.auto_import});await flush();closeModal();toast('Inbox preference saved.');break;
 case 'studio-polish':if(editable())polishDialog('humanize');break;
 case 'studio-deslop':if(editable())polishDialog('deslop');break;
 case 'studio-audit':await auditDialog();break;
 case 'studio-run-craft':{const mode=$('#craft-mode').value,instruction=$('#craft-instruction').value;closeModal();await startJob(mode,instruction);break;}
 case 'studio-compare':await flush();compareDialog();break;
 case 'studio-accept-craft':await flush();state.p=await api('/projects/'+state.p.id+'/craft/accept',{version:state.p.version,acknowledge_warnings:!!$('#craft-ack')?.checked});closeModal();render();toast('Edit accepted. The original is preserved in Versions.');break;
 case 'studio-discard-craft':await flush();state.p=await api('/projects/'+state.p.id+'/craft/discard',{version:state.p.version});closeModal();render();break;
 case 'studio-codex-login':{if(busy())throw new Error('Finish or cancel the active job before changing sign-in.');$('#s-provider').value='codex';$('#s-base_url').value='https://api.openai.com/v1';if(state.settings.provider!=='codex')for(const id of ['model','editor_model','extraction_model'])$('#s-'+id).value='';await saveSettings();const r=await api('/codex/login',{});$('#codex-status').innerHTML=esc(r.note)+' <a href="'+esc(r.auth_url)+'" target="_blank" rel="noopener noreferrer">Open sign-in page</a>';break;}
 case 'studio-codex-status':{await saveSettings();$('#codex-status').textContent='Checking Codex…';const r=await api('/codex/status');$('#codex-status').textContent=r.signed_in?`Connected as ${r.email||'your ChatGPT account'}${r.plan?' · '+r.plan:''}. Select Codex as the writing provider. A blank model uses the Codex default.`:r.error||'Not signed in yet. Complete the browser sign-in and check again.';break;}
 case 'studio-codex-logout':await api('/codex/logout',{});$('#codex-status').textContent='Signed out of GraphPaper’s Codex account. Other Codex installations were not signed out.';break;
 }};
document.addEventListener('input',event=>{if(event.target.id==='voice-strength')$('#voice-strength-value').textContent=event.target.value;});
document.addEventListener('change',event=>{if(event.target.id==='s-provider'&&event.target.value==='codex'){$('#s-base_url').value='https://api.openai.com/v1';for(const id of ['model','editor_model','extraction_model'])$('#s-'+id).value='';$('#s-model').placeholder='Blank = your Codex default model';}});
setInterval(()=>{const focused=document.activeElement;if(!state.p?.auto_import||studio.syncing||busy()||$('.modal')||Object.keys(pending).length||state.save==='Saving…'||document.hidden||focused?.matches('input,textarea,select'))return;scanFolder(false).catch(e=>console.warn('Project inbox:',e.message));},5000);
if(state.projects.length||state.p)render();
