/* Named voice graphs are a separate reusable library, not another pile of evidence. */
'use strict';
const voicesUI={list:[],current:null,node:null,job:null,poll:null};
const voicesPriorRender=render;
render=function(){voicesPriorRender();const sidebar=$('.sidebar');if(sidebar&&!$('[data-action="voices-library"]',sidebar)){const b=document.createElement('div');b.className='voices-sidebar';b.innerHTML=btn('Voices','voices-library','graph','small');sidebar.append(b);}};
const voicesPriorWelcome=welcomeHTML;
welcomeHTML=function(){return voicesPriorWelcome()+`<div class="voices-welcome">${btn('My reusable voices','voices-library','graph','small')}<span class="hint">Build a voice once. Select it in any project.</span></div>`;};
const voicesPriorDialog=voiceDialog;
voiceDialog=function(){voicesPriorDialog();$('.modal-body').insertAdjacentHTML('afterbegin',`<div class="voices-banner"><strong>${esc(state.p.voice_profile.library_id?'Saved voice: '+state.p.voice_profile.name:'Keep a voice, not a pile of articles')}</strong><p class="hint">Saved voice graphs work across projects without retraining. The current brief can override any habit, including force and vocabulary.</p><div class="row wrap mt12">${btn('Choose a saved voice','voices-library','graph','small')}${btn('Save as reusable voice','voices-save-project','plus','primary small')}${state.p.voice_profile.library_id?btn('View graph overlay','voices-overlay','branch','small'):''}</div></div>`);};
const voicesPriorSources=sourcesHTML;
sourcesHTML=function(){const p=state.p,original=p.sources,count=original.filter(s=>s.role==='voice').length;try{p.sources=original.filter(s=>s.role!=='voice');return (count?`<div class="voices-banner"><strong>${count} legacy voice sample(s) kept outside this evidence view</strong><p class="hint">No originals were deleted. Save the learned voice once and reuse its graph.</p>${btn('Manage writing voice','studio-voice','graph','small')}</div>`:'')+voicesPriorSources();}finally{p.sources=original;}};
function voiceSVG(graph,overlayMode=false){const nodes=graph.nodes||[],edges=graph.edges||[];if(!nodes.length)return '<p class="hint panel-body">No style graph yet. Add a habit, paste instructions or learn from training pieces.</p>';const width=680,height=420,positions={};nodes.forEach((n,i)=>{const angle=2*Math.PI*i/Math.max(1,nodes.length);positions[n.id]=[width/2+Math.cos(angle)*250,height/2+Math.sin(angle)*145];});return `<svg class="voice-graph" viewBox="0 0 ${width} ${height}" role="img" aria-label="${overlayMode?'Voice and evidence overlay':'Reusable voice graph'}">${edges.map(e=>{const a=positions[e.source],b=positions[e.target];return a&&b?`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" class="${e.layer==='overlay'?'overlay-link':''}"><title>${esc(e.relation)}</title></line>`:'';}).join('')}${nodes.map(n=>{const [x,y]=positions[n.id];return `<g class="voice-graph-node ${n.layer==='evidence'?'evidence-node':''}" ${overlayMode?'':`data-action="voices-node" data-id="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(n.label)}"`} transform="translate(${x} ${y})"><circle r="${n.kind==='voice'?14:9}"></circle><text y="25" text-anchor="middle">${esc(n.label.length>24?n.label.slice(0,22)+'…':n.label)}</text><title>${esc(n.instruction||n.label)}</title></g>`;}).join('')}</svg>`;}
async function showVoiceLibrary(id=null){if(state.p)await flush();voicesUI.list=await api('/voices');if(id)voicesUI.current=await api('/voices/'+id);else voicesUI.current=null;paintVoices();}
function paintVoices(){const v=voicesUI.current;showModal('My voices','Reusable graphs of how you write. Learn once; apply wherever you choose.',`<div class="voices-layout"><aside><div class="row wrap">${btn('New voice','voices-new','plus','small')}${btn('Import graph','voices-import','upload','small')}</div><div class="voices-list">${voicesUI.list.map(x=>`<button data-action="voices-open" data-id="${esc(x.id)}" class="voice-item ${v?.id===x.id?'active':''}"><strong>${esc(x.name)}</strong><small>${x.nodes} nodes · ${x.samples} training pieces</small></button>`).join('')||'<p class="hint mt20">Your named voices will live here, independently of projects.</p>'}</div></aside><section>${v?voiceEditor(v):`<h3>Create once, reuse.</h3><p class="hint mt12">Build a mini graph from your writing or your own style directions. Training articles stay here; applying a voice copies only its compact graph.</p>${state.p?btn('Save this project’s voice','voices-save-project','plus','primary mt20'):''}`}</section></div>`,v?btn('Save graph','voices-save','check','primary small')+(state.p?btn('Use in this project','voices-apply','arrow','small'):'')+btn('Export voice','voices-export','download','small'):'',true);}
function voiceEditor(v){const g=v.graph,n=g.nodes.find(x=>x.id===voicesUI.node)||g.nodes[0];voicesUI.node=n?.id||null;return `<div class="form-grid"><div><label for="saved-voice-name">Voice name</label><input id="saved-voice-name" value="${esc(v.profile.name)}"></div><div><label for="saved-voice-strength">Influence, %</label><input id="saved-voice-strength" type="number" min="0" max="100" value="${v.profile.strength}"></div></div>${voiceSVG(g)}<div class="row wrap">${btn('Add writing habit','voices-add-node','plus','small')}${n?btn('Remove selected habit','voices-remove-node','trash','small ghost'):''}</div>${n?`<div class="form-grid mt12"><div><label for="voice-node-label">Habit label</label><input id="voice-node-label" value="${esc(n.label)}"></div><div><label for="voice-node-weight">Importance, 0–1</label><input id="voice-node-weight" type="number" min="0" max="1" step="0.05" value="${n.weight}"></div><div class="form-full"><label for="voice-node-instruction">Your instruction · power language is welcome</label><textarea id="voice-node-instruction" rows="3">${esc(n.instruction)}</textarea></div></div>`:''}<details class="mt20"><summary>Build graph from written style directions</summary><textarea id="saved-voice-instructions" rows="5" class="mt12" placeholder="Keep the sarcasm. Use strong language when I ask. A sharp ending, not a committee conclusion.">${esc(v.profile.instructions)}</textarea>${btn('Convert directions to graph','voices-from-text','graph','small mt12')}</details><details class="mt20"><summary>Training pieces (${v.samples.length}) · separate from article evidence</summary><div class="row wrap mt12">${btn('Upload writing','voices-upload','upload','small')}${btn('Paste writing','voices-paste','file','small')}${btn('Article URL','voices-url','link','small')}${btn('Learn / rebuild graph','voices-learn','spark','primary small')}</div><p id="voices-job-status" class="hint mt12">${v.needs_relearning?'Training changed; the previous saved graph remains usable until you explicitly relearn.':'Applying this voice needs no model call and no re-upload.'}</p>${v.samples.map(s=>`<div class="studio-sample"><button class="text-link spacer" data-action="voices-read-sample" data-id="${esc(s.id)}">${esc(s.title)}</button><small>${s.words} words</small>${ibtn('Delete this training piece','voices-delete-sample','trash',`data-id="${esc(s.id)}"`)}</div>`).join('')}</details><p class="hint mt20">Your current article instructions override saved style preferences. This graph is not a vocabulary filter. Updating the library does not silently rewrite voices already applied to other projects.</p><button class="text-link danger mt12" data-action="voices-delete">Delete saved voice</button>`;}
function collectVoiceNode(){const v=voicesUI.current;if(!v)return;if($('#saved-voice-name'))v.profile.name=$('#saved-voice-name').value;if($('#saved-voice-strength'))v.profile.strength=Number($('#saved-voice-strength').value);const n=v.graph.nodes.find(x=>x.id===voicesUI.node);if(n&&$('#voice-node-instruction')){n.label=$('#voice-node-label').value;n.instruction=$('#voice-node-instruction').value;n.weight=Number($('#voice-node-weight').value);}}
async function saveVoiceGraph(){collectVoiceNode();const v=voicesUI.current;voicesUI.current=await api('/voices/'+v.id,{version:v.version,name:v.profile.name,strength:v.profile.strength,graph:v.graph},'PATCH');voicesUI.list=await api('/voices');return voicesUI.current;}
async function voiceDownload(path,name){if(window.pywebview?.api?.save_export){const r=await window.pywebview.api.save_export(voicesUI.current.id,'voice');if(r.error)throw new Error(r.error);if(r.saved)toast('Voice graph exported.');return;}const r=await fetch('/api'+path,{headers:{'X-GraphPaper':'1'},credentials:'same-origin'});if(!r.ok)throw new Error('Voice export failed.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function pollVoiceJob(){const id=voicesUI.job;if(!id)return;try{const j=await api('/jobs/'+id);if($('#voices-job-status'))$('#voices-job-status').textContent=j.state+' · '+j.usage.calls+' model calls'+(j.error?' · '+j.error:'');if(['queued','running'].includes(j.state)){voicesUI.poll=setTimeout(pollVoiceJob,900);return;}voicesUI.job=null;if(j.state==='completed'){const vid=voicesUI.current?.id;await showVoiceLibrary(vid);toast('Voice graph learned and saved. Ready to reuse.');}else toast(j.error||'Voice learning did not complete.',true);}catch(e){voicesUI.job=null;toast(e.message,true);}}
const voicesPriorAction=handleAction;
handleAction=async function(el){const a=el.dataset.action;if(!a.startsWith('voices-'))return voicesPriorAction(el);switch(a){
case 'voices-library':return showVoiceLibrary();
case 'voices-open':voicesUI.node=null;return showVoiceLibrary(el.dataset.id);
case 'voices-new':{const v=await api('/voices',{name:'My new voice'});return showVoiceLibrary(v.id);}
case 'voices-save-project':{if(!state.p||!editable())return;await flush();if($('#voice-name')){const profile={...state.p.voice_profile,name:$('#voice-name').value,instructions:$('#voice-instructions').value,strength:Number($('#voice-strength').value),enabled:$('#voice-enabled').checked};if(profile.instructions!==state.p.voice_profile.instructions)profile.graph={};queueSave({voice_profile:profile});await flush();}const v=await api('/voices',{project_id:state.p.id,version:state.p.version});return showVoiceLibrary(v.id);}
case 'voices-node':collectVoiceNode();voicesUI.node=el.dataset.id;paintVoices();break;
case 'voices-add-node':collectVoiceNode();{const g=voicesUI.current.graph;if(g.nodes.length>=32)throw new Error('Use at most 32 compact writing habits.');const id=uid();g.nodes.push({id,label:'New writing habit',instruction:'',kind:'style',weight:1,targets:['all']});if(g.nodes.length>1)g.edges.push({source:g.nodes[0].id,target:id,relation:'expresses'});voicesUI.node=id;paintVoices();}break;
case 'voices-remove-node':collectVoiceNode();{const g=voicesUI.current.graph,id=voicesUI.node;g.nodes=g.nodes.filter(n=>n.id!==id);g.edges=g.edges.filter(e=>e.source!==id&&e.target!==id);voicesUI.node=null;paintVoices();}break;
case 'voices-save':await saveVoiceGraph();paintVoices();toast('Voice graph saved.');break;
case 'voices-from-text':{collectVoiceNode();const v=voicesUI.current;voicesUI.current=await api('/voices/'+v.id,{version:v.version,name:v.profile.name,instructions:$('#saved-voice-instructions').value},'PATCH');paintVoices();break;}
case 'voices-apply':{if(!state.p||!editable())return;const v=await saveVoiceGraph();await flush();state.p=await api('/projects/'+state.p.id+'/voice/apply',{version:state.p.version,voice_id:v.id});closeModal();syncSummary();render();toast('Voice applied. No training articles copied and no model call made.');break;}
case 'voices-export':await saveVoiceGraph();return voiceDownload('/voices/'+voicesUI.current.id+'/export','voice-graph.json');
case 'voices-import':chooseFile('.json',false,async files=>{const file=files[0];if(file.size>100000)throw new Error('Choose a compact voice export, not the training corpus.');const v=await api('/voices/import',JSON.parse(await file.text()));await showVoiceLibrary(v.id);});break;
case 'voices-upload':{const vid=voicesUI.current.id;chooseFile('.pdf,.docx,.txt,.md,.html,.htm',true,async files=>{for(const f of files){const body=new FormData();body.append('file',f);await api('/voices/'+vid+'/samples/file',body);}await showVoiceLibrary(vid);});break;}
case 'voices-paste':case 'voices-url':showModal(a==='voices-url'?'Add writing from an article URL':'Add a writing sample','Training stays in the voice library, outside every project’s evidence.',`<label for="voice-sample-title">Title</label><input id="voice-sample-title" value="Writing sample"><label class="mt12" for="voice-sample-text">${a==='voices-url'?'Article URL':'Your writing'}</label><textarea id="voice-sample-text" rows="8"></textarea>`,btn('Add training piece',a==='voices-url'?'voices-submit-url':'voices-submit-text','plus','primary'));break;
case 'voices-submit-text':case 'voices-submit-url':{const vid=voicesUI.current.id;const value=$('#voice-sample-text').value;await api('/voices/'+vid+'/samples/'+(a==='voices-submit-url'?'url':'text'),a==='voices-submit-url'?{url:value}:{title:$('#voice-sample-title').value,text:value});return showVoiceLibrary(vid);}
case 'voices-learn':{const v=await saveVoiceGraph();const j=await api('/voices/'+v.id+'/learn',{version:v.version});voicesUI.job=j.id;paintVoices();pollVoiceJob();break;}
case 'voices-read-sample':{const s=await api('/voices/'+voicesUI.current.id+'/samples/'+el.dataset.id);showModal(s.title,'Voice training only.',`<div class="source-text">${esc(s.text)}</div>`,btn('Back to voice','voices-open','back','small',`data-id="${esc(voicesUI.current.id)}"`),true);break;}
case 'voices-delete-sample':if(confirm('Delete this training piece from the saved voice? Applied voices and original project files remain intact.')){const v=voicesUI.current;await api('/voices/'+v.id+'/samples/'+el.dataset.id,{version:v.version},'DELETE');return showVoiceLibrary(v.id);}break;
case 'voices-delete':if(confirm('Delete this saved voice? Projects already using it keep their own compact copies.')){await api('/voices/'+voicesUI.current.id,{version:voicesUI.current.version},'DELETE');return showVoiceLibrary();}break;
case 'voices-overlay':{await flush();const g=await api('/projects/'+state.p.id+'/voice/overlay');showModal('Voice + project graph','Namespaced layers guide expression without altering the research graph.',voiceSVG(g,true)+`<p class="hint">${esc(g.scope.note)}</p>`,'',true);break;}
}};
document.addEventListener('keydown',e=>{const node=e.target.closest?.('.voice-graph-node[data-action]');if(node&&['Enter',' '].includes(e.key)){e.preventDefault();handleAction(node).catch(err=>toast(err.message,true));}});
